### PR TITLE
Add Msys support

### PR DESCRIPTION
**Pull request by RickBarretto**
## What I've done

added support to msys2
  1. copied `windows` config
  2. renamed to `msys2`
  3. replaced `7z a` by `tar czf`
    1. and replaced `{{runner.os}}` by `WindowsMsys2`
  5. added `msys2` into `upload > needs`

### CODE REVIEW

**Review by drkameleon — APPROVED** [review]
Looks good to me! 😄

**Comment by drkameleon** [comment]
The CI builds fail but apparently it has nothing to do with your PR (I had missed some dependencies almost for the past 2 months 😕 ). 

I'm merging it and will fix the pending issue myself later on... 😉

**Comment by drkameleon** [comment]
Related: https://github.com/arturo-lang/nightly/issues/4

**Comment by RickBarretto** [comment]
😉 Okay! I saw it, the fail was on BSD and Nix.

@drkameleon 
I saw a strange thing.

[Package *nix (ubuntu-latest, full)](https://github.com/arturo-lang/nightly/actions/runs/3112681875/jobs/5046384058#logs) shows:

> install: cannot stat './bin/arturo': No such file or directory
tar: arturo: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

IDK if it's the same problem I had on Msys, but my terminal showed to me `Cannot stat: No such file or directory` when install.sh tried to copy from temporary directory ([`ARTURO_TMP_DIR`](https://github.com/arturo-lang/arturo-lang.io/blob/0eb756476e5730e69521d25bf25c0f5a067df5b6/installer/stable.sh#L101)) to arturo's bin path ([`BIN_PATH`](https://github.com/arturo-lang/arturo-lang.io/blob/0eb756476e5730e69521d25bf25c0f5a067df5b6/installer/stable.sh#L219)) . It's the reason because I did [`msys_download_arturo` function](https://github.com/arturo-lang/arturo-lang.io/blob/0eb756476e5730e69521d25bf25c0f5a067df5b6/installer/stable.sh#L217) download directly on `$HOME/.arturo/bin/` instead of `ARTURO_TMP_DIR`.

Again, IDK if it is the problem, but my Msys showed to me the same message.

**Comment by drkameleon** [comment]
> install: cannot stat './bin/arturo': No such file or directory

The `install: cannot stat './bin/arturo': No such file or directory` part is because it cannot find an arturo binary in the first place.

And the reason behind that is that there was a compilation error (namely, I forgot to pre-install a few dependencies that have arised since like 2 months ago, mainly the MPFR: https://www.mpfr.org/) 😉

**Pull request merged**
