### PR TITLE
Fix binary building

### LINKED ISSUE #5: Binary releases are not being uploaded since 2023/11/26.
Since then, it's just uploading the source-code.
image

### PR DESCRIPTION
**Pull request by RickBarretto**
- Fixes #5

### CODE REVIEW

**Comment by RickBarretto** [comment]
Some notes:

* Raspberry support was deprecated
* Windows builds are breaking before the build command for what it seems to
* Web builds are breaking for unknown problems, should log it first.

**Comment by RickBarretto** [comment]
@drkameleon, can you give me a hint here?

For some reason, I'm not being able to build web locally, I'm getting:

```
C:\Users\rickb\Downloads\nim-2.0.0_x64\nim-2.0.0\lib\impure\re.nim(11, 10) Error: This library needs to be compiled with a c-like backend, and depends on PCRE; See jsre for JS backend.
```

But, it's [working on the main CI][ci]. Although, it's not uploading artifacts...

[ci]: https://github.com/arturo-lang/arturo/actions/runs/7505509656/job/20434884911

**Comment by RickBarretto** [comment]
I need to know why FreeBSD is not triggering too...

**Comment by RickBarretto** [comment]
@drkameleon, I disabled MSYS builds. I think this should be a better way to create these files and avoid code repetition, or completely move to `.gz` files or `.zip` ones.

I also disabled Web builds, since this is not working right now. And it needs to be fixed ASAP. #1524.

I just don't know what is happening with FreeBSD that is never triggered...

**Comment by RickBarretto** [comment]
If you want to see if this is partially working right now, and fix other issues later, I can open new issues.

**Comment by drkameleon** [comment]
Give me some time and I'll have a look into everything! :)

**Re: builds (as far as I can tell right now at least)**

- Let's focus on getting Linux, macOS, Windows (mini + full) building 100% fine, and we can deal with the rest later
- Web builds is the next thing I would try (now, have I tested it locally after the last big PRs? The truth is I haven't. And given the nature e.g. of the Quantities/Rational values, I wouldn't be surprised at all if we ended having to disable entire feature so as to make the Web builds work)
- FreeBSD/NetBSD/OpenBSD could easily work too (the mini builds at least), I just remember a couple of issues that bothered me (Full builds are a different story, but sb that is knowledgeable enough should actually make them work too)
- 32-bit version of ... anything are tricky to say the least. Basically, I would see 2 options: either enabling them selectively (but this would involve tons of `when defined...` in the code and could potentially lead to a complete mess), or stick to just 64-bits

**Comment by RickBarretto** [comment]
Having that being told, I think this PR would be ready to merge so.
At least, this would make releases work again for Windows, MacOS and Linux again.

**Comment by drkameleon** [comment]
I'm looking into the PR and it all looks fine. However, the `Upload` part is supposedly failing...
That's the one that would - normally - upload our "Nightly build", nope? 🤔 

I'll have to look into it and I'll merge as soon as this is ok... (perhaps, I should do sth on my end? let me know in case you discover sth first! 😉 )

**Comment by RickBarretto** [comment]
> That's the one that would - normally - upload our "Nightly build", nope? 🤔

Yep. That is a good question, I thought it broke due to web builds... But even disabled, it returns: `Resource not accessible by integration`.

**Comment by RickBarretto** [comment]
@drkameleon, for what I'm reading. This seems to be an issue with permissions.
So I can't touch this;

**Comment by drkameleon** [comment]
> @drkameleon, for what I'm reading. This seems to be an issue with permissions. So I can't touch this;

Since I'm ultra-confused with this, and I'm not even sure if it has to do with the fact that it's in a PR, I'm merging this and we'll see (either way, what can go wrong? it's already wrong... lol)

Let's see...

**Review by drkameleon — APPROVED** [review]

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Pull request merged**
