### PR TITLE
Add mac releases

### PR DESCRIPTION
**Pull request by ErikSchierboom**
I'm trying to add mac releases (well, at least the mini version), but I'm getting an error:

```
fatal error: 'gmp.h' file not found
#include <gmp.h>
```

I've tried `brew install gmp`, but apparently that was already installed. Any ideas?

### CODE REVIEW

**Comment by RickBarretto** [comment]
@drkameleon, have a look on this when you can. 😉

**Comment by drkameleon** [comment]
@ErikSchierboom Thanks a lot for all the effort. 🚀 

Re: Nightlies, I have just created a new PR that will solve the issue.

Basically, as I mention there too, since we have a GitHub action for this type of things, the most sensible approach would be to use that for creating the nightly builds as well - it's just that I hadn't managed to find the time to implement it!

So, let's see, let's see! 😉

**Comment by ErikSchierboom** [comment]
Nice! I see your PR is having the same issue I have: https://github.com/arturo-lang/nightly/actions/runs/9468896759/job/26086316389?pr=8

**Comment by drkameleon** [comment]
> Nice! I see your PR is having the same issue I have: https://github.com/arturo-lang/nightly/actions/runs/9468896759/job/26086316389?pr=8

Well, basically it's just a placeholder - for now. I didn't change anything at all (other than removing the Arturo repo/submodule), that's why the error is the same 😉 

Goal of the day: properly integrate the Arturo action in this repo, and hoping for the best! haha 🚀

**Pull request closed without merging**
